language: scala
scala:
  - 2.11.12
jdk: openjdk8
env:
  SBT_OPTS="-Xmx4096M"
script:
  - sudo apt-get -y install make
  - make test-all-linux
  - make dist-cdh5
  - make dist-cdh6
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
