language: scala
scala:
  - 2.11.12
jdk: openjdk8
env:
  SBT_OPTS="-Xmx4096M"
  VERSION=$TRAVIS_TAG
  DEPLOY_REPO=parcels-dev
  CDH_VERSION=6
script:
  - sudo apt-get -y install make
  - make test-all-linux
  - make dist-cdh5
  - make dist-cdh6
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
deploy:
  provider: script
  script: build-support/deploy.sh
  on:
    tags: true
    all_branches: true
