site_name: Pulse
theme: readthedocs
pages:
  - index.md
  - installation.md
  - collection-roller.md
  - log-appender.md
  - log-collector.md
  - alerting-engine.md
  - visualizations.md
  - building.md
  - contributing.md

