#!/bin/bash
spark2-submit \
--files src/main/resources/log4j-async.xml \
--conf "spark.driver.extraJavaOptions=-Dlog4j.configuration=file:src/main/resources/log4j-async.xml" \
--conf "spark.executor.extraJavaOptions=-Dlog4j.configuration=file:log4j-async.xml" \
--class io.phdata.pams.example.SparkLog4jExample target/scala-2.11/log-example-assembly-2.0.2-cdh5.jar

